apiVersion: v1
kind: Pod
metadata:
  name: nasty-pod
  namespace: default
spec:
  containers:
  - image: docker.io/nginx
    name: nasty-pod
    resources:
      requests:
        cpu: "200m"   #changed by gptscript
